title: SE Conference Deadlines # (Maintained by @tdegueul)
description: This list is heavily biased towards my research topics.<br>I shall not be held liable for any missed deadline due to inaccuracies on this website ;)
author: Thomas Degueule

domain: "https://tdegueul.github.io/se-deadlines/"
baseurl: /se-deadlines

twitter_username: tdegueul
#twitter_hashtag: machinelearning
github_username: tdegueul
github_repo: se-deadlines

markdown: kramdown
#ga_id: UA-36274081-2
